"""
Olytic Plugin Compiler
======================
Deterministic file generator. Takes a validated PluginSpec and writes a complete,
standards-compliant plugin to disk. No LLM involvement after this point.

Usage:
    python3 plugin-compiler.py <spec.json>              # compile from spec file
    python3 plugin-compiler.py --dry-run <spec.json>    # print file list without writing
    python3 plugin-compiler.py --validate-dir <dir>     # validate an existing plugin directory

Output:
    Plugins/<plugin-name>/src-<plugin-name>/...     # relative to workspace root

The compiler is invoked by Aule after the LLM translation layer produces a clean
PluginSpec. Aule calls parse_spec() first — if that succeeds, the compiler runs.
If parse_spec() fails, Aule surfaces the errors to the user and loops back.

--validate-dir mode:
    Reads an existing plugin directory, reconstructs a PluginSpec-compatible dict
    from the actual files, and validates it through Pydantic. Aule uses this after
    Update Mode edits — surgical fixes stay surgical, but the final result is still
    spec-verified. Exits 0 on pass, 1 on fail.

Version: 1.1.0
"""

from __future__ import annotations

import json
import os
import re
import sys
import textwrap
import zipfile
from datetime import datetime, timezone
from pathlib import Path

# plugin-spec.py must be on the path
sys.path.insert(0, str(Path(__file__).parent))
from plugin_spec import PluginSpec, MemoryScope, ComponentType, Platform, parse_spec


# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────

COMPILER_VERSION = "1.1.0"
AULE_VERSION     = "0.3.0"
# Telemetry and vault writes use the olytic-gateway MCP connector (org-installed, optional).
# No hardcoded gateway URL — the MCP server resolves transport and auth from the session.


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def today_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def indent(text: str, n: int = 2) -> str:
    return textwrap.indent(text, " " * n)


def write_file(path: Path, content: str, dry_run: bool = False) -> None:
    if dry_run:
        print(f"  [DRY] {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  ✅ {path}")


# ─────────────────────────────────────────────
# FILE GENERATORS
# ─────────────────────────────────────────────

def gen_plugin_json(spec: PluginSpec) -> str:
    manifest = {
        "name":        spec.plugin_name,
        "version":     spec.version,
        "description": spec.description,
        "author":      {"name": spec.author.name, "email": spec.author.email},
        "keywords":    spec.keywords,
        "hooks":       "hooks/hooks.json",
    }
    if spec.connectors:
        manifest["connectors"] = [
            {"id": c.id, "required": c.required, "scopes": c.scopes}
            for c in spec.connectors
        ]
    return json.dumps(manifest, indent=2, ensure_ascii=False)


def gen_readme(spec: PluginSpec) -> str:
    components_list = "\n".join(
        f"- **{c.name}** ({c.type.value}) — {c.purpose}"
        for c in spec.components
    )
    constraints_list = "\n".join(f"- {c}" for c in spec.constraints) or "- None declared"
    connectors_list = "\n".join(
        f"- `{c.id}` ({'required' if c.required else 'optional'})"
        for c in spec.connectors
    ) or "- None (standalone)"

    return f"""# {spec.plugin_name}

> {spec.description}

## Purpose

{spec.plugin_purpose}

## Components

{components_list}

## Constraints

{constraints_list}

## Integrations

{connectors_list}

## Memory

**Scope:** {spec.memory_scope.value}
{gen_readme_memory_section(spec)}

## Claude OS Identity

**Dimension:** {spec.dimension or "Not specified"}
**Upstream plugins:** {", ".join(spec.upstream_plugins) or "None"}
**Downstream plugins:** {", ".join(spec.downstream_plugins) or "None"}

---
*Generated by Aule Plugin Compiler v{COMPILER_VERSION} on {today_str()}*
"""


def gen_readme_memory_section(spec: PluginSpec) -> str:
    if spec.memory_scope == MemoryScope.ephemeral:
        return "Session-only. No data is retained between sessions."
    if spec.memory_scope == MemoryScope.persistent:
        ma = spec.memory_access
        ac = ma.access_control.value if ma else "private"
        readers = (", ".join(ma.authorized_readers) if ma and ma.authorized_readers else "N/A")
        return (
            f"Data is retained between sessions via vault.\n"
            f"**Access control:** {ac}\n"
            f"**Authorized readers:** {readers}\n"
            f"**Retention:** {ma.retention_days if ma else 90} days"
        )
    if spec.memory_scope == MemoryScope.retrieval:
        rc = spec.retrieval_config
        sources = (", ".join(rc.sources) if rc else "not configured")
        return f"RAG/retrieval mode. Sources: {sources}"
    return ""


def gen_skill(spec: PluginSpec, component) -> str:
    trigger_phrases = "\n  ".join(component.trigger_phrases)
    constraints_block = ""
    if spec.constraints:
        constraints_block = "\n## Constraints\n\nThis plugin must NOT be used to:\n" + \
                            "\n".join(f"- {c}" for c in spec.constraints)

    return f"""---
name: {component.name}
description: >
  {component.purpose}
  Use this skill when the user says: "{component.trigger_phrases[0]}", "{component.trigger_phrases[1]}",
  "{component.trigger_phrases[2]}", "{component.trigger_phrases[3]}"
  {("or: " + ", ".join(f'"{p}"' for p in component.trigger_phrases[4:])) if len(component.trigger_phrases) > 4 else ""}
version: {spec.version}
---

# {component.name}

{component.purpose}

## Trigger Phrases

This skill activates when the user says:
  {trigger_phrases}
{constraints_block}

## Operating Principles

Before acting, map the existing environment. Use search/glob to understand what exists.
Source of truth: local files take precedence over conversational context.
Atomic operations: make the smallest change necessary.
Verification gate: every write is followed by a confirmation check.
No hallucination: if a value is not found, report "Not Found" — never guess.

## Core Logic

[TODO: Define the step-by-step logic for {component.name}]

1. [Step 1 — discovery / read phase]
2. [Step 2 — processing / reasoning phase]
3. [Step 3 — output / write phase]
4. Verification: confirm output is valid before presenting to user

## Output Format

[TODO: Define what this skill returns to the user]

Telemetry: This skill logs all invocations via {spec.plugin_name}-telemetry.
"""


def gen_agent(spec: PluginSpec, component) -> str:
    trigger_phrases = "\n  ".join(component.trigger_phrases)
    return f"""---
name: {component.name}
description: >
  {component.purpose}
  Invoke when the user says: "{component.trigger_phrases[0]}", "{component.trigger_phrases[1]}",
  "{component.trigger_phrases[2]}", "{component.trigger_phrases[3]}"
version: {spec.version}
---

# {component.name}

{component.purpose}

## Trigger Phrases

  {trigger_phrases}

## Agent Phases

This agent orchestrates a multi-step workflow. Execute each phase in order.

### Phase 1: Discovery
- Map the existing environment before taking action
- Identify relevant files, data, and current state
- Report: what exists, what is missing, what needs to change

### Phase 2: Planning
- Based on Phase 1 findings, determine the sequence of actions
- Identify any permission gates (destructive actions, bulk changes >5 files)
- Present the plan to the user if it involves irreversible steps

### Phase 3: Execution
- Execute the planned actions atomically
- Use targeted edits, not full rewrites
- After each write: run verification check

### Phase 4: Verification
- Confirm all outputs are valid
- Run any relevant validation scripts
- Report: what was done, what changed, what to check manually

## Operating Principles

Discovery first. Source of truth. Atomic operations. Verification gate. No hallucination. Permission gate.

[TODO: Add domain-specific logic for {component.name}]

Telemetry: This agent logs all invocations via {spec.plugin_name}-telemetry.
"""


def gen_command(spec: PluginSpec, component) -> str:
    trigger_phrases = "\n  ".join(component.trigger_phrases)
    return f"""---
name: {component.name}
description: >
  {component.purpose}
  Use when: "{component.trigger_phrases[0]}", "{component.trigger_phrases[1]}",
  "{component.trigger_phrases[2]}", "{component.trigger_phrases[3]}"
---

# {component.name}

{component.purpose}

## Usage

```
{component.name} [options]
```

## What This Command Does

[TODO: Define what this command does step by step]

1. [Step 1]
2. [Step 2]
3. Verification: confirm output before completing

## Trigger Phrases

  {trigger_phrases}

## Notes

[TODO: Add any flags, edge cases, or notes]
"""


def gen_telemetry_skill(spec: PluginSpec) -> str:
    return f"""---
name: {spec.plugin_name}-telemetry
description: >
  Auto-loaded telemetry skill for {spec.plugin_name}. Tracks usage events, constraint violations,
  and user feedback. Loads automatically — do not invoke directly.
version: {spec.version}
---

# {spec.plugin_name} Telemetry

> **Schema:** Fetches the canonical `telemetry-event` schema at runtime from `olytic-core` by invoking the `olytic-core-schemas` skill.
> Do NOT bake field definitions in. Do NOT read from filesystem paths — use the skill invocation only.
> This works whether olytic-core is a mounted workspace folder or an installed Organizational Plugin.

## Schema Runtime Behavior

Before logging any event:

```
invoke skill: olytic-core-schemas
schema: telemetry-event

→ Use the returned base_fields and event_fields as the authoritative event shape
→ Do NOT cache — re-invoke at each session start
```

**Canonical event types (8):**
`skill_invoke`, `decision_trace`, `feedback`, `violation`, `not_found_reported`,
`verification_gate`, `permission_gate`, `agent_trigger`

## Transport

Call the **`log_telemetry` tool** via the `olytic-gateway` MCP connector.
The connector is org-installed and optional — if absent, skip silently and continue.
Do NOT include `user_id`, `org_id`, or `client_id` in the payload; the MCP server
resolves and injects them from the active session. No credentials in skill files.
Silent operation — never announce a write to the user.

## Base Fields (all events)

| Field | Value |
|-------|-------|
| timestamp | ISO 8601 UTC with Z suffix |
| event | One of the 8 canonical event types |
| plugin | "{spec.plugin_name}" |
| plugin_version | "{spec.version}" |
| component | Name of the invoking skill/agent/command |
| platform | "{spec.platform.value}" (build-time constant — do not change at runtime) |

## What to Log

### skill_invoke / agent_trigger
Log on every invocation. Additional field: `trigger` (5–15 word paraphrase of what triggered it, no PII).

### decision_trace
Log when a significant interpretation or routing decision is made.
Additional fields: `input_summary`, `reasoning` (array, 2–3 items), `output_summary`, `confidence` (high/medium/low).

### violation
Log when the user tries something outside this plugin's constraints.
Additional fields: `violation_type`, `description`, `constraint_violated`, `action_taken`.

### verification_gate
Log after every verification check.
Additional fields: `result` (pass/fail), `description`.

### permission_gate
Log when asking the user to confirm a destructive or bulk action.
Additional fields: `action_type`, `description`, `user_decision`.

### feedback
Log when the user expresses satisfaction or dissatisfaction.
Additional fields: `sentiment` (positive/negative), `context`, `output_summary`.

### not_found_reported
Log when something is searched for and not found.
Additional field: `description`.

## Example Event

```json
{{
  "timestamp": "{now_iso()}",
  "event": "skill_invoke",
  "plugin": "{spec.plugin_name}",
  "plugin_version": "{spec.version}",
  "component": "{spec.components[0].name if spec.components else spec.plugin_name}",
  "platform": "{spec.platform.value}",
  "trigger": "user asked to [describe action in 5-15 words]"
}}
```

`platform` is a build-time constant — hardcoded at plugin generation time, never inferred at runtime.
`user_id`, `org_id`, and `client_id` are injected server-side by the olytic-gateway MCP connector — do NOT include them in the payload.

Telemetry logging is always silent. Never surface a log write to the user.
"""


def gen_session_summarizer(spec: PluginSpec) -> str:
    """Only generated for persistent memory plugins."""
    return f"""---
name: {spec.plugin_name}-session-summarizer
description: >
  Auto-invoked at SessionClose for {spec.plugin_name}. Writes a structured session summary
  to the vault via olytic-gateway. Silent operation — no user action required.
  Only active when memory_scope=persistent.
version: {spec.version}
hook: SessionClose
---

# {spec.plugin_name} Session Summarizer

Automatically captures episodic memory at the end of every session.
Fires on the `SessionClose` hook. Silent — never announces its operation.

## Schema Runtime Behavior

At each invocation, fetch both schemas from `olytic-core`:

```
invoke skill: olytic-core-schemas
schema: session-summary
→ Use the returned fields as the authoritative content shape

invoke skill: olytic-core-schemas
schema: vault-entry
→ Use the returned fields as the authoritative envelope structure
```

Do NOT cache. Do NOT read from filesystem paths. Re-invoke on every SessionClose.
This works whether olytic-core is a mounted workspace folder or an installed Organizational Plugin.

## Step-by-Step Protocol

**Step 1:** Invoke `olytic-core-schemas` for `session-summary`. Use its fields for the content payload.

**Step 2:** Invoke `olytic-core-schemas` for `vault-entry`. Use its fields for the envelope wrapper.

**Step 3:** Assess session substance. If purely conversational with no decisions or changes, produce a minimal summary (primary_topic + narrative only).

**Step 4:** Populate content fields:
- `primary_topic` — one sentence (required)
- `key_decisions` — 2–6 decisions affecting future sessions
- `corrections` — errors caught and corrected
- `new_knowledge` — things discovered this session
- `open_threads` — unresolved questions left for future
- `narrative` — 100–300 words, briefing-style

**Step 5:** Apply quality gate:
- `primary_topic` non-empty ✓
- `narrative` 100–300 words ✓
- At least one of `key_decisions`, `new_knowledge`, `open_threads` non-empty ✓
- If gate fails → log `violation` event, skip vault write

**Step 6:** Wrap in envelope:
```json
{{
  "entry_id": "[new UUID]",
  "session_id": "[session UUID if known, otherwise omit]",
  "plugin": "{spec.plugin_name}",
  "plugin_version": "{spec.version}",
  "session_timestamp": "[ISO 8601 UTC]",
  "entry_type": "session_summary",
  "loop": "plugin",
  "platform": "{spec.platform.value}",
  "schema_version": "1.2.0",
  "content": {{ ... }}
}}
```

`platform` is a build-time constant — do not infer at runtime.
`loop` defaults to `"plugin"` for auto-generated session summaries.
`entry_type` uses underscores to match `memory_entries.entity_type` exactly.

**Step 7:** Call the **`write_vault_entry` tool** via the `olytic-gateway` MCP connector.
The connector is org-installed and optional — if absent, skip silently and continue.
Do NOT include `user_id` or `client_id`; the gateway resolves and injects them server-side via `auth.uid()`.

**Step 8:** Log `verification_gate` event: result (pass/fail), entry_id.

## Operating Principles

- Silent: never tell the user a summary is being written
- No PII in summaries
- Corrections and new_knowledge are optional but valuable
- If vault write fails: log the failure silently, do not surface to user
"""


def gen_hooks_json(spec: PluginSpec) -> str:
    hooks: dict = {}

    # PostToolUse — always present to trigger repackager on source changes
    plugin_src = f"Plugins/{spec.plugin_name}/src-{spec.plugin_name}"
    hooks["PostToolUse"] = [
        {
            "matcher": "Write|Edit",
            "hooks": [
                {
                    "type": "prompt",
                    "prompt": (
                        f"A file was just written or edited. "
                        f"Check if the path contains '{plugin_src}'. "
                        f"If YES — a {spec.plugin_name} source file changed. "
                        f"Automatically invoke the aule-plugin-repackager skill: "
                        f"'A plugin source file was just modified at [file path]. "
                        f"Repackage {spec.plugin_name} and verify the .zip is in sync.'"
                    ),
                    "timeout": 20
                }
            ]
        }
    ]

    # SessionClose — only for persistent memory plugins
    if spec.memory_scope == MemoryScope.persistent:
        hooks["SessionClose"] = [
            {
                "matcher": ".*",
                "hooks": [
                    {
                        "type": "prompt",
                        "prompt": (
                            f"The session is closing. "
                            f"Invoke the {spec.plugin_name}-session-summarizer skill "
                            f"to capture episodic memory and write the session summary to the vault."
                        ),
                        "timeout": 30
                    }
                ]
            }
        ]

    return json.dumps(hooks, indent=2, ensure_ascii=False)


def gen_metadata(spec: PluginSpec) -> str:
    meta = {
        "name":         spec.plugin_name,
        "version":      spec.version,
        "description":  spec.description,
        "author":       {"name": spec.author.name, "email": spec.author.email},
        "keywords":     spec.keywords,
        "generated_at": now_iso(),
        "generated_by": f"aule-plugin-compiler v{COMPILER_VERSION}",
        "aule_version": AULE_VERSION,
        "memory_scope": spec.memory_scope.value,
        "connectors":   [c.id for c in spec.connectors],
        "components":   [{"name": c.name, "type": c.type.value} for c in spec.components],
        "status":       "active",
    }
    return json.dumps(meta, indent=2, ensure_ascii=False)


# ─────────────────────────────────────────────
# MAIN COMPILER
# ─────────────────────────────────────────────

def compile_plugin(spec: PluginSpec, workspace_root: Path, dry_run: bool = False) -> Path:
    """
    Write all plugin files to disk.

    Returns the path to the generated src directory.
    """
    name     = spec.plugin_name
    parent   = workspace_root / "Plugins" / name
    src      = parent / f"src-{name}"
    dot_cp   = src / ".claude-plugin"

    print(f"\n🔨 Compiling plugin: {name} v{spec.version}")
    print(f"   Output: {src}\n")

    # ── Manifest ──────────────────────────────
    write_file(dot_cp / "plugin.json", gen_plugin_json(spec), dry_run)

    # ── README ────────────────────────────────
    write_file(src / "README.md", gen_readme(spec), dry_run)

    # ── Hooks ─────────────────────────────────
    write_file(src / "hooks" / "hooks.json", gen_hooks_json(spec), dry_run)

    # ── Telemetry skill (always) ───────────────
    write_file(
        src / "skills" / f"{name}-telemetry" / "SKILL.md",
        gen_telemetry_skill(spec),
        dry_run
    )

    # ── Session summarizer (persistent only) ──
    if spec.memory_scope == MemoryScope.persistent:
        write_file(
            src / "skills" / f"{name}-session-summarizer" / "SKILL.md",
            gen_session_summarizer(spec),
            dry_run
        )

    # ── User-declared components ───────────────
    for component in spec.components:
        if component.type == ComponentType.skill:
            write_file(
                src / "skills" / component.name / "SKILL.md",
                gen_skill(spec, component),
                dry_run
            )
        elif component.type == ComponentType.agent:
            write_file(
                src / "agents" / f"{component.name}.md",
                gen_agent(spec, component),
                dry_run
            )
        elif component.type == ComponentType.command:
            write_file(
                src / "commands" / f"{component.name}.md",
                gen_command(spec, component),
                dry_run
            )

    # ── Metadata sidecar (parent level) ───────
    write_file(parent / f"{name}.metadata.json", gen_metadata(spec), dry_run)

    # ── Package (zip) ─────────────────────────
    if not dry_run:
        zip_path = parent / f"{name}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in src.rglob("*"):
                if file_path.is_file() and ".DS_Store" not in str(file_path):
                    zf.write(file_path, file_path.relative_to(src))
        print(f"  📦 {zip_path}")

    print(f"\n✅ {name} compiled successfully.")
    print(f"   Files written to: {src}")
    return src


# ─────────────────────────────────────────────
# VALIDATION REPORT
# ─────────────────────────────────────────────

def validate_output(src: Path, spec: PluginSpec) -> list[str]:
    """Post-compile sanity checks. Returns list of failure messages."""
    failures = []
    name = spec.plugin_name

    required = [
        src / ".claude-plugin" / "plugin.json",
        src / "README.md",
        src / "hooks" / "hooks.json",
        src / "skills" / f"{name}-telemetry" / "SKILL.md",
    ]
    if spec.memory_scope == MemoryScope.persistent:
        required.append(src / "skills" / f"{name}-session-summarizer" / "SKILL.md")

    for path in required:
        if not path.exists():
            failures.append(f"MISSING: {path.relative_to(src)}")

    # Validate plugin.json is parseable
    plugin_json_path = src / ".claude-plugin" / "plugin.json"
    if plugin_json_path.exists():
        try:
            manifest = json.loads(plugin_json_path.read_text())
            valid_keys = {"name", "version", "description", "author", "keywords",
                          "hooks", "connectors"}
            extra = set(manifest.keys()) - valid_keys
            if extra:
                failures.append(f"plugin.json has invalid keys: {extra}")
        except json.JSONDecodeError as e:
            failures.append(f"plugin.json is not valid JSON: {e}")

    return failures


# ─────────────────────────────────────────────
# DIRECTORY → SPEC EXTRACTOR
# ─────────────────────────────────────────────

def extract_spec_from_dir(plugin_dir: Path) -> tuple[dict, list[str]]:
    """
    Reconstruct a PluginSpec-compatible dict from an existing plugin directory.

    Reads:
      .claude-plugin/plugin.json  → identity fields, connectors
      README.md                   → purpose, constraints, memory scope hints
      hooks/hooks.json            → memory scope (SessionClose → persistent)
      skills/*/SKILL.md           → component entries (skill type)
      agents/*.md                 → component entries (agent type)
      commands/*.md               → component entries (command type)

    Returns (raw_dict, pre_validation_warnings).
    pre_validation_warnings are soft issues found during extraction (e.g. missing
    optional fields) — not Pydantic errors. The raw_dict is then fed to parse_spec()
    which does the real validation.
    """
    warnings: list[str] = []
    raw: dict = {}

    # ── plugin.json ───────────────────────────
    pj_path = plugin_dir / ".claude-plugin" / "plugin.json"
    if not pj_path.exists():
        warnings.append("MISSING: .claude-plugin/plugin.json — cannot extract identity fields")
    else:
        try:
            pj = json.loads(pj_path.read_text())
        except json.JSONDecodeError as e:
            warnings.append(f"INVALID JSON: .claude-plugin/plugin.json — {e}")
            pj = {}

        raw["plugin_name"]  = pj.get("name", "")
        raw["version"]      = pj.get("version", "0.1.0")
        raw["description"]  = pj.get("description", "")
        raw["sublabel"]     = pj.get("sublabel", "Plugin")
        raw["icon"]         = pj.get("icon", "🔌")
        raw["keywords"]     = pj.get("keywords", [])

        author_raw = pj.get("author", {})
        if isinstance(author_raw, dict):
            raw["author"] = {
                "name":  author_raw.get("name", "Olytic Solutions"),
                "email": author_raw.get("email", "support@olyticsolutions.com"),
            }
        else:
            raw["author"] = {"name": str(author_raw), "email": "support@olyticsolutions.com"}

        # Connectors — exclude olytic-gateway (auto-injected by validator)
        raw_connectors = []
        for c in pj.get("connectors", []):
            if isinstance(c, dict) and c.get("id") != "olytic-gateway":
                raw_connectors.append({
                    "id":       c.get("id", "unknown"),
                    "required": c.get("required", True),
                    "scopes":   c.get("scopes", []),
                })
        raw["connectors"] = raw_connectors

    # ── README.md ─────────────────────────────
    readme_path = plugin_dir / "README.md"
    readme_text = ""
    if not readme_path.exists():
        warnings.append("MISSING: README.md — cannot extract purpose or constraints")
    else:
        readme_text = readme_path.read_text(encoding="utf-8")

    # Extract plugin_purpose: first non-empty paragraph after the title
    purpose = ""
    in_purpose = False
    for line in readme_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and not in_purpose:
            in_purpose = True
            continue
        if in_purpose:
            if stripped.startswith(">"):
                purpose = stripped.lstrip("> ").strip()
                break
            if stripped and not stripped.startswith("#"):
                purpose = stripped
                break
            if stripped.startswith("#"):
                break
    raw["plugin_purpose"] = purpose or raw.get("description", "")

    # Extract key_functions: look for ## Components or ## Key Functions section
    key_functions: list[str] = []
    in_section = False
    for line in readme_text.splitlines():
        stripped = line.strip()
        if re.match(r"^## (Components|Key Functions|Features)", stripped, re.I):
            in_section = True
            continue
        if in_section:
            if stripped.startswith("##"):
                break
            m = re.match(r"^[-*]\s+\*?\*?([^*\-—:]+)", stripped)
            if m:
                key_functions.append(m.group(1).strip())
    raw["key_functions"] = key_functions if key_functions else ["[TODO: describe key functions]"]

    # Extract constraints: look for ## Constraints or ## Boundaries section
    constraints: list[str] = []
    in_constraints = False
    for line in readme_text.splitlines():
        stripped = line.strip()
        if re.match(r"^## (Constraints|Boundaries|Out of Scope)", stripped, re.I):
            in_constraints = True
            continue
        if in_constraints:
            if stripped.startswith("##"):
                break
            m = re.match(r"^[-*]\s+(.+)", stripped)
            if m:
                constraints.append(m.group(1).strip())
    raw["constraints"] = constraints

    # Extract memory scope: check README text, then hooks.json
    memory_scope = "ephemeral"
    if re.search(r"memory.?scope.*persistent|persistent.*memory", readme_text, re.I):
        memory_scope = "persistent"
    elif re.search(r"memory.?scope.*retrieval|retrieval.*memory", readme_text, re.I):
        memory_scope = "retrieval"

    # ── hooks.json → confirm persistent if SessionClose present ──
    hooks_path = plugin_dir / "hooks" / "hooks.json"
    if hooks_path.exists():
        try:
            hooks_data = json.loads(hooks_path.read_text())
            if "SessionClose" in hooks_data:
                memory_scope = "persistent"
        except json.JSONDecodeError:
            warnings.append("INVALID JSON: hooks/hooks.json — could not read hooks")

    raw["memory_scope"] = memory_scope

    # memory_access: synthesize a minimal valid block if persistent
    if memory_scope == "persistent":
        access_ctrl = "private"
        if re.search(r"access.?control.*shared|shared.*access", readme_text, re.I):
            access_ctrl = "shared"
        elif re.search(r"access.?control.*org.wide|org.wide.*access", readme_text, re.I):
            access_ctrl = "org-wide"
        raw["memory_access"] = {
            "access_control":     access_ctrl,
            "authorized_readers": [],
            "retention_days":     90,
            "purge_on_removal":   True,
        }

    # ── Components: skills ────────────────────
    components: list[dict] = []
    skills_dir = plugin_dir / "skills"
    plugin_name = raw.get("plugin_name", "")

    if skills_dir.exists():
        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir():
                continue
            skill_name = skill_dir.name
            # Skip auto-generated skills — they're written by the compiler, not spec-declared
            if skill_name in (f"{plugin_name}-telemetry", f"{plugin_name}-session-summarizer"):
                continue
            skill_md = skill_dir / "SKILL.md"
            purpose_str, triggers = _parse_component_md(skill_md, warnings)
            components.append({
                "name":            skill_name,
                "type":            "skill",
                "purpose":         purpose_str,
                "trigger_phrases": triggers,
            })

    # ── Components: agents ────────────────────
    agents_dir = plugin_dir / "agents"
    if agents_dir.exists():
        for agent_md in sorted(agents_dir.glob("*.md")):
            agent_name = agent_md.stem
            purpose_str, triggers = _parse_component_md(agent_md, warnings)
            components.append({
                "name":            agent_name,
                "type":            "agent",
                "purpose":         purpose_str,
                "trigger_phrases": triggers,
            })

    # ── Components: commands ──────────────────
    commands_dir = plugin_dir / "commands"
    if commands_dir.exists():
        for cmd_md in sorted(commands_dir.glob("*.md")):
            cmd_name = cmd_md.stem
            purpose_str, triggers = _parse_component_md(cmd_md, warnings)
            components.append({
                "name":            cmd_name,
                "type":            "command",
                "purpose":         purpose_str,
                "trigger_phrases": triggers,
            })

    if not components:
        warnings.append("No user-declared components found (skills/agents/commands) — plugin has no domain logic")
    raw["components"] = components

    # ── Minimal defaults for optional fields ──
    raw.setdefault("telemetry_signals",        [])
    raw.setdefault("optimizer_feedback_points", [])
    raw.setdefault("success_metrics",          [])
    raw.setdefault("upstream_plugins",         [])
    raw.setdefault("downstream_plugins",       [])
    raw.setdefault("dimension",                None)

    return raw, warnings


def _parse_component_md(md_path: Path, warnings: list[str]) -> tuple[str, list[str]]:
    """
    Parse a skill/agent/command .md file.
    Returns (purpose_string, [trigger_phrases]).

    Extracts:
      - description from YAML frontmatter → purpose + triggers
      - Falls back to first H1 body paragraph if no frontmatter
    """
    if not md_path.exists():
        warnings.append(f"MISSING: {md_path}")
        return "[TODO: describe purpose]", ["[TODO trigger 1]", "[TODO trigger 2]",
                                            "[TODO trigger 3]", "[TODO trigger 4]"]

    text = md_path.read_text(encoding="utf-8")

    # Extract YAML frontmatter block
    fm_match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    description_raw = ""
    if fm_match:
        fm_block = fm_match.group(1)
        # Handle block scalar (description: >) and inline description
        desc_block = re.search(r"^description:\s*>\s*\n((?:  .+\n?)+)", fm_block, re.MULTILINE)
        desc_inline = re.search(r"^description:\s*['\"]?(.+?)['\"]?\s*$", fm_block, re.MULTILINE)
        if desc_block:
            description_raw = textwrap.dedent(desc_block.group(1)).strip()
        elif desc_inline:
            description_raw = desc_inline.group(1).strip()

    if not description_raw:
        # Fallback: use first non-empty line after the first H1
        for line in text.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#") and not stripped.startswith("---"):
                description_raw = stripped
                break

    # Split description into purpose (first sentence/line) and trigger phrases (remaining)
    # Convention: description starts with purpose, then "Use when the user says: ..."
    # or contains quoted phrases like "review this proposal"
    purpose = description_raw.split("\n")[0].strip() if description_raw else "[TODO: describe purpose]"

    # Extract quoted trigger phrases from description
    triggers = re.findall(r'"([^"]{4,80})"', description_raw)

    # Deduplicate while preserving order
    seen: set[str] = set()
    unique_triggers: list[str] = []
    for t in triggers:
        if t not in seen:
            seen.add(t)
            unique_triggers.append(t)

    # Pad to minimum 4 if short (Pydantic will catch this as an error, which is the intent)
    while len(unique_triggers) < 4:
        unique_triggers.append(f"[TODO trigger {len(unique_triggers) + 1}]")

    return purpose, unique_triggers


def validate_dir(plugin_dir: Path) -> None:
    """
    Entry point for --validate-dir mode.

    Extracts a PluginSpec-compatible dict from the directory, validates it through
    Pydantic, prints a structured report, and exits 0 (pass) or 1 (fail).
    """
    if not plugin_dir.exists():
        print(f"❌ Directory not found: {plugin_dir}")
        sys.exit(1)

    plugin_name = plugin_dir.name
    print(f"\n🔍 Validating plugin directory: {plugin_dir}\n")

    # ── Step 1: Extract ───────────────────────
    raw, extraction_warnings = extract_spec_from_dir(plugin_dir)

    if extraction_warnings:
        print("⚠️  Extraction warnings (file-level issues found before spec validation):\n")
        for w in extraction_warnings:
            print(f"  • {w}")
        print()

    # ── Step 2: Pydantic validation ───────────
    spec, errors = parse_spec(raw)

    if errors:
        print("❌ Spec validation failed — issues found in this plugin:\n")
        for e in errors:
            print(f"  • {e}")
        print()
        _print_validate_dir_summary(plugin_name, extraction_warnings, errors, passed=False)
        sys.exit(1)

    # ── Step 3: File-level structural checks ──
    # These mirror validate_output() but for an already-compiled directory
    structural_failures: list[str] = []
    name = raw.get("plugin_name", plugin_dir.name)

    required_files = [
        plugin_dir / ".claude-plugin" / "plugin.json",
        plugin_dir / "README.md",
        plugin_dir / "hooks" / "hooks.json",
        plugin_dir / "skills" / f"{name}-telemetry" / "SKILL.md",
    ]
    if raw.get("memory_scope") == "persistent":
        required_files.append(plugin_dir / "skills" / f"{name}-session-summarizer" / "SKILL.md")

    for path in required_files:
        if not path.exists():
            structural_failures.append(f"MISSING required file: {path.relative_to(plugin_dir)}")

    # Validate agent frontmatter: no <example> inside --- block
    agents_dir = plugin_dir / "agents"
    if agents_dir.exists():
        for agent_md in agents_dir.glob("*.md"):
            text = agent_md.read_text(encoding="utf-8")
            fm = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
            if fm and "<example>" in fm.group(1):
                structural_failures.append(
                    f"YAML ERROR: {agent_md.name} has <example> tags inside frontmatter block — "
                    f"move them to after the closing ---"
                )
            # Check for unquoted colons in single-line description
            if fm:
                desc_m = re.search(r"^description:\s*(?!>)(.+)", fm.group(1), re.MULTILINE)
                if desc_m and ": " in desc_m.group(1):
                    structural_failures.append(
                        f"YAML ERROR: {agent_md.name} description contains ': ' on a single line — "
                        f"use 'description: >' block scalar format"
                    )

    # Validate skill frontmatter: name, description, version present
    skills_dir = plugin_dir / "skills"
    if skills_dir.exists():
        for skill_dir in skills_dir.iterdir():
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                structural_failures.append(f"MISSING: skills/{skill_dir.name}/SKILL.md")
                continue
            text = skill_md.read_text(encoding="utf-8")
            fm = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
            if not fm:
                structural_failures.append(f"skills/{skill_dir.name}/SKILL.md: missing YAML frontmatter")
            else:
                for required_key in ("name:", "description:", "version:"):
                    if required_key not in fm.group(1):
                        structural_failures.append(
                            f"skills/{skill_dir.name}/SKILL.md: frontmatter missing '{required_key[:-1]}' field"
                        )

    if structural_failures:
        print("❌ Structural validation failed:\n")
        for f in structural_failures:
            print(f"  • {f}")
        print()
        _print_validate_dir_summary(plugin_name, extraction_warnings, structural_failures, passed=False)
        sys.exit(1)

    _print_validate_dir_summary(plugin_name, extraction_warnings, [], passed=True)
    print(f"\n✅ {plugin_name} passed spec validation — safe to package.\n")


def _print_validate_dir_summary(
    name: str,
    warnings: list[str],
    errors: list[str],
    passed: bool
) -> None:
    status = "✅ PASSED" if passed else "❌ FAILED"
    print(f"── Validation Summary: {name} ──")
    print(f"   Status:   {status}")
    print(f"   Warnings: {len(warnings)}")
    print(f"   Errors:   {len(errors)}")
    if not passed:
        print()
        print("   Aule: read the errors above and ask the user for the missing information.")
        print("   Fix the source files, then re-run --validate-dir.")


# ─────────────────────────────────────────────
# CLI ENTRY POINT
# ─────────────────────────────────────────────

def main() -> None:
    args = sys.argv[1:]

    # ── --validate-dir mode ───────────────────
    if "--validate-dir" in args:
        idx = args.index("--validate-dir")
        if idx + 1 >= len(args):
            print("Usage: python3 plugin-compiler.py --validate-dir <plugin-dir>")
            sys.exit(1)
        validate_dir(Path(args[idx + 1]))
        return

    # ── Normal compile / dry-run mode ─────────
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    if not args:
        print("Usage:")
        print("  python3 plugin-compiler.py [--dry-run] <spec.json>")
        print("  python3 plugin-compiler.py --validate-dir <plugin-dir>")
        sys.exit(1)

    spec_path = Path(args[0])
    if not spec_path.exists():
        print(f"❌ Spec file not found: {spec_path}")
        sys.exit(1)

    raw = json.loads(spec_path.read_text())
    spec, errors = parse_spec(raw)

    if errors:
        print("❌ Spec validation failed — Aule needs more information:\n")
        for e in errors:
            print(f"  • {e}")
        sys.exit(1)

    # Workspace root = 4 levels up from src-aule/tools/
    workspace_root = Path(__file__).parent.parent.parent.parent.parent

    if dry_run:
        print("🔍 DRY RUN — no files will be written\n")

    src = compile_plugin(spec, workspace_root, dry_run=dry_run)

    if not dry_run:
        failures = validate_output(src, spec)
        if failures:
            print("\n⚠️  Post-compile validation failures:")
            for f in failures:
                print(f"   • {f}")
            sys.exit(1)
        else:
            print("✅ Post-compile validation passed.")


if __name__ == "__main__":
    main()
